version: '3'

networks:
  order-service:
    driver: bridge

services:
  app:
    container_name: order-service
    build: .
    environment:
      DB_HOST: db
      RABBITMQ_SERVER_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
      - "50051:50051"
      - "8080:8080"
    networks:
      - order-service

  db:
    container_name: mysql
    image: mysql:8.3
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    volumes:
      - ./sql/migrations/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"
    networks:
      - order-service

  adminer:
    container_name: adminer
    image: adminer:4
    restart: always
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - "8081:8080"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.16-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    networks:
      - order-service
